version: "3.5"

services:
  web:
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    ports:
      - "4087:4000"
    env_file:
      - config/dev/public.env
      - config/dev/secrets.env
    depends_on:
      - db
      - search
      # - redis
      # - dgraph
    volumes:
      - type: bind
        source: .
        target: /opt/app
      # - type: bind
      #   source: /usr/share/dict/words
      #   target: /usr/share/dict/words
  db:
    image: postgis/postgis:12-3.0-alpine
    volumes:
      - "./data/postgres/dev:/var/lib/postgresql/data"
    # ports:
    #   - "5432:5432"
    env_file:
      - config/dev/public.env
      - config/dev/secrets.env
  dbeaver:
    image: dalongrong/cloudbeaver
    ports:
      - "8978:8978"
    depends_on:
      - db
    # volumes:
    #   - "/var/log/cloudbeaver.log:/var/log/cloudbeaver/server.log"
  # redis:
  #   image: redislabs/redisgraph
  #   ports:
  #     - "6379:6379"
  # dgraph:
  #   image: dgraph/standalone:v2.0.0-beta
  #   ports:
  #     - "8001:8000"
  #     - "8080:8080"
  #     - "9080:9080"
  search:
    image: getmeili/meilisearch:latest
    ports:
      - "7787:7700"
    volumes:
      - "./data/search/dev:/data.ms"
    env_file:
      - config/dev/public.env
      - config/dev/secrets.env
